// 司机创建运单的mutation定义
export const RESET_TRANSIT = 'RESET_TRANSIT'
export const SUBMIT_TRANSIT = 'SUBMIT_TRANSIT'
export const ADD_TRANSIT_INFO = 'ADD_TRANSIT_INFO'
// 司机查看个人运单详情的mutation定义
export const DRIVER_TRANSIT_DETAIL = 'DRIVER_TRANSIT_DETAIL'
export const GET_DRIVER_TRANSIT_DETAIL_FAILURE = 'GET_DRIVER_TRANSIT_DETAIL_FAILURE'
// 司机个人运单列表的mutation定义
export const DRIVER_TRANSIT_LIST = 'DRIVER_TRANSIT_LIST'
export const GET_DRIVER_TRANSIT_LIST_FAILURE = 'GET_DRIVER_TRANSIT_LIST_FAILURE'
// 搜索公司页面的mutations定义
export const SEARCH_COMPANGY_LIST = 'SEARCH_COMPANGY_LIST'
export const SEARCH_COMPANGY_LIST_FAILURE = 'SEARCH_COMPANGY_LIST_FAILURE'
// 搜索货物页面的mutations定义
export const SEARCH_GOODS_LIST = 'SEARCH_GOODS_LIST'
export const SEARCH_GOODS_LIST_FAILURE = 'SEARCH_GOODS_LIST_FAILURE'
// 司机筛选货物页面的mutations定义
export const RESET_DRIVER_TRANSIT_FILTERS = 'RESET_DRIVER_TRANSIT_FILTERS'
export const SUBMIT_DRIVER_TRANSIT_FILTERS = 'SUBMIT_DRIVER_TRANSIT_FILTERS'
export const ADD_DRIVER_TRANSIT_FILTER_INFO = 'ADD_DRIVER_TRANSIT_FILTER_INFO'
