// 司机创建运单的mutation定义
export const RESET_TRANSIT = 'RESET_TRANSIT'
export const SUBMIT_TRANSIT = 'SUBMIT_TRANSIT'
export const ADD_TRANSIT_INFO = 'ADD_TRANSIT_INFO'
// 司机查看个人运单详情的mutation定义
export const DRIVER_TRANSIT_DETAIL = 'DRIVER_TRANSIT_DETAIL'
export const GET_DRIVER_TRANSIT_DETAIL_FAILURE = 'GET_DRIVER_TRANSIT_DETAIL_FAILURE'
// 司机个人运单列表的mutation定义
export const DRIVER_TRANSIT_LIST = 'DRIVER_TRANSIT_LIST'
export const GET_DRIVER_TRANSIT_LIST_FAILURE = 'GET_DRIVER_TRANSIT_LIST_FAILURE'
// 搜索公司页面的mutations定义
export const SEARCH_COMPANGY_LIST = 'SEARCH_COMPANGY_LIST'
export const SEARCH_COMPANGY_LIST_FAILURE = 'SEARCH_COMPANGY_LIST_FAILURE'
// 搜索货物页面的mutations定义
export const SEARCH_GOODS_LIST = 'SEARCH_GOODS_LIST'
export const SEARCH_GOODS_LIST_FAILURE = 'SEARCH_GOODS_LIST_FAILURE'
// 司机筛选货物页面的mutations定义
export const RESET_DRIVER_TRANSIT_FILTERS = 'RESET_DRIVER_TRANSIT_FILTERS'
export const SUBMIT_DRIVER_TRANSIT_FILTERS = 'SUBMIT_DRIVER_TRANSIT_FILTERS'
export const ADD_DRIVER_TRANSIT_FILTER_INFO = 'ADD_DRIVER_TRANSIT_FILTER_INFO'
// ----------------------------会计部分-----------------------------
// 会计未审核运单列表
export const ACCOUNT_UNCHECK_LIST = 'ACCOUNT_UNCHECK_LIST'
export const GET_ACCOUNT_UNCHECK_LIST_FAILURE = 'GET_ACCOUNT_UNCHECK_LIST_FAILURE'
export const ADD_ACCOUNT_UNCHECK_ITEM = 'ADD_ACCOUNT_UNCHECK_ITEM'
// 会计未审核运单详情
export const ACCOUNT_UNCHECK_DETAIL = 'ACCOUNT_UNCHECK_DETAIL'
export const GET_ACCOUNT_UNCHECK_DETAIL_FAILURE = 'GET_ACCOUNT_UNCHECK_DETAIL_FAILURE'
// 会计个人审核过列表
export const ACCOUNT_CHECKED_LIST = 'ACCOUNT_CHECKED_LIST'
export const GET_ACCOUNT_CHECKED_LIST_FAILURE = 'GET_ACCOUNT_CHECKED_LIST_FAILURE'
export const ADD_ACCOUNT_CHECKED_ITEM = 'ADD_ACCOUNT_CHECKED_ITEM'
// 会计个人已经审核详情
export const ACCOUNT_CHECKED_DETAIL = 'ACCOUNT_CHECKED_DETAIL'
export const GET_ACCOUNT_CHECKED_DETAIL_FAILURE = 'GET_ACCOUNT_CHECKED_DETAIL_FAILURE'
// 会计未定价运单列表
export const ACCOUNT_UNPRICE_LIST = 'ACCOUNT_UNPRICE_LIST'
export const GET_ACCOUNT_UNPRICE_LIST_FAILURE = 'GET_ACCOUNT_UNPRICE_LIST_FAILURE'
export const ADD_ACCOUNT_UNPRICE_ITEM = 'ADD_ACCOUNT_UNPRICE_ITEM'
// 会计未定价运单详情
export const ACCOUNT_UNPRICE_DETAIL = 'ACCOUNT_UNPRICE_DETAIL'
export const GET_ACCOUNT_UNPRICE_DETAIL_FAILURE = 'GET_ACCOUNT_UNPRICE_DETAIL_FAILURE'
// 会计个人已定价列表
export const ACCOUNT_PRICED_LIST = 'ACCOUNT_PRICED_LIST'
export const GET_ACCOUNT_PRICED_LIST_FAILURE = 'GET_ACCOUNT_PRICED_LIST_FAILURE'
export const ADD_ACCOUNT_PRICED_ITEM = 'ADD_ACCOUNT_PRICED_ITEM'
// 会计个人已定价详情
export const ACCOUNT_PRICED_DETAIL = 'ACCOUNT_PRICED_DETAIL'
export const GET_ACCOUNT_PRICED_DETAIL_FAILURE = 'GET_ACCOUNT_PRICED_DETAIL_FAILURE'
// 会计个人公司运输核算列表
export const ACCOUNT_COMPANY_FUND_LIST = 'ACCOUNT_COMPANY_FUND_LIST'
export const GET_ACCOUNT_COMPANY_FUND_LIST_FAILURE = 'GET_ACCOUNT_COMPANY_FUND_LIST_FAILURE'
// 会计个人公司运输核算详细信息
export const ACCOUNT_COMPANY_FUND_DETAIL = 'ACCOUNT_COMPANY_FUND_DETAIL'
export const GET_ACCOUNT_COMPANY_FUND_DETAIL_FAILURE = 'GET_ACCOUNT_COMPANY_FUND_DETAIL_FAILURE'
// 会计个人中心的设置
export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN'
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT'
